version: '3.8'
services:
  app:
    container_name: 75
    image: 'oven/bun:1.1.29'
    command: >
      sh -c "
        bun install --production --frozen-lockfile &&
        bun run build &&
        bun run start
      "
    ports:
      - '8025:3000'
    volumes:
      - './:/app'
    working_dir: /app
    environment:
      - NODE_ENV=production
